name: Build, Push to ECR, and Deploy to EKS with Quarkus app
on:
  pull_request:
    branches:
      - master
jobs:
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile the code
        run: mvn compile

      - name: Run unit tests
        run: mvn test

      - name: Run PMD analysis
        run: mvn pmd:check

  build-push-deploy:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Native Image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./mvnw clean package -Dquarkus.container-image.tag=${IMAGE_TAG}

      - name: Configure kubectl for EKS
        run: aws eks update-kubeconfig --name quarkus --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f target/kubernetes/kubernetes.yml

  integration-test:
    needs: build-push-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Integration Test
        run: |
          echo "Testing the deployed application"
          response=$(curl -s http://aeaf7296a50444e25b82e4145761ef25-13049291.eu-west-1.elb.amazonaws.com/hello)
          echo "Response from application: $response"
          [[ "$response" == *"Hello"* ]] || exit 1

  smoke-test:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Integration Test
        run: |
          echo "Testing the deployed application"
          response=$(curl -s http://aeaf7296a50444e25b82e4145761ef25-13049291.eu-west-1.elb.amazonaws.com/hello)
          echo "Response from application: $response"
          [[ "$response" == *"Hello"* ]] || exit 1