name: Build, Push to ECR, and Deploy to EKS with Quarkus

on:
  pull_request:
    branches:
      - master

jobs:
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile the code
        run: mvn compile

      - name: Run unit tests
        run: mvn test

      - name: Run PMD analysis
        run: mvn pmd:check

  #  integration-test:
  #    needs: commit-stage
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Set up JDK 17
  #        uses: actions/setup-java@v2
  #        with:
  #          java-version: '17'
  #          distribution: 'temurin'
  #
  #      - name: Cache Maven packages
  #        uses: actions/cache@v2
  #        with:
  #          path: ~/.m2
  #          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  #          restore-keys: ${{ runner.os }}-m2
  #
  #      - name: Run integration tests
  #        run: mvn verify

  build-push-deploy:
    needs: commit-stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      #      - name: Update Application Version
      #        run: mvn versions:set -DnewVersion=${{ github.sha }}-SNAPSHOT

      - name: Build and Push Native Image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./mvnw clean package -Dquarkus.container-image.tag=${IMAGE_TAG}

      - name: Prepare Kubernetes Deployment Files
        run: |
          bash prepare-k8s-files.sh

      # Configurar kubectl para EKS
      - name: Configure kubectl for EKS
        run: aws eks update-kubeconfig --name quarkus --region ${{ secrets.AWS_REGION }}

      #kubectl apply -f target/kubernetes/kubernetes.yml
      # Despliegue en EKS
      - name: Deploy to EKS
        run: |
          ./prepare-k8s-files.sh
          ./deploy-green-loadbalancer.sh
