apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus-app
          image: 116858595749.dkr.ecr.eu-west-1.amazonaws.com/quarkus:latest
          ports:
            - containerPort: 8080
